services:
  telegram-bot-resume-ia:
    build:
      context: ./
    env_file:
      - .env
    environment:
      - GO_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
